CREATE DATABASE IF NOT EXISTS mobile bank;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  national_id CHAR(10) NOT NULL UNIQUE,
  card_number CHAR(16) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  balance BIGINT DEFAULT 0
);